In [4]:
# This is Ben Robin's 7.1
import numpy as np
numbers= np.array([2, 3, 4, 5, 7, 11])
type(numbers)
np.ndarray
numbers

array([ 2,  3,  4,  5,  7, 11])

In [5]:
np.array([[1,2,3],[4,5,6]])


array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
#self check 7.2 Ben Robin
np.array([x for x in range(2,21,2)])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
np.array([[2,4,6,8,10],[1,3,5,7,9]])

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [10]:
# 7.3 Ben Robin 
integers = np.array([[1,2,3],[4,5,6]])
integers

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
floats = np.array([0.0,0.1,0.2,0.3,0.4])
floats

array([0. , 0.1, 0.2, 0.3, 0.4])

In [13]:
integers.dtype

dtype('int64')

In [14]:
floats.dtype

dtype('float64')

In [15]:
integers.ndim

2

In [16]:
floats.ndim

1

In [17]:
integers.shape

(2, 3)

In [18]:
floats.shape

(5,)

In [19]:
integers.size

6

In [20]:
integers.itemsize

8

In [21]:
floats.size

5

In [22]:
floats.itemsize

8

In [24]:
for row in integers:
    for column in row:
        print(column, end=' ')
    print()

1 2 3 
4 5 6 


In [25]:
for i in integers.flat:
    print(i, end=' ')

1 2 3 4 5 6 

In [26]:
# 7.3 self check Ben Robin 
a = np.array([[2,4,6,8,10], [1,3,5,7,9]])
a.ndim

2

In [27]:
a.shape

(2, 5)

In [28]:
# 7.4 Ben Robin 
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [30]:
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [31]:
np.full((4,10),55)

array([[55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55, 55, 55, 55, 55, 55]])

In [32]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [33]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [34]:
np.arange(10,1,-2)

array([10,  8,  6,  4,  2])

In [36]:
np.linspace(0.0,1.0,num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [37]:
np.arange(1, 21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [40]:
np.arange(1,5001).reshape(4,1250)

array([[   1,    2,    3, ..., 1248, 1249, 1250],
       [1251, 1252, 1253, ..., 2498, 2499, 2500],
       [2501, 2502, 2503, ..., 3748, 3749, 3750],
       [3751, 3752, 3753, ..., 4998, 4999, 5000]])

In [41]:
np.arange(1,100001).reshape(100,1000)

array([[     1,      2,      3, ...,    998,    999,   1000],
       [  1001,   1002,   1003, ...,   1998,   1999,   2000],
       [  2001,   2002,   2003, ...,   2998,   2999,   3000],
       ...,
       [ 97001,  97002,  97003, ...,  97998,  97999,  98000],
       [ 98001,  98002,  98003, ...,  98998,  98999,  99000],
       [ 99001,  99002,  99003, ...,  99998,  99999, 100000]])

In [42]:
# 7.5 Ben Robin self check 
np.arange(2,41,2).reshape(4,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [43]:
#Ben Robin 7.6 
import random

%timeit rolls_list =\
    [random.randrange(1,7)for i in range(0,6_000_000)]


7.25 s ± 158 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [44]:
%timeit rolls_array = np.random.randint(1,7,6_000_000)

118 ms ± 4.07 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
import numpy as np

In [6]:
import random

In [9]:
np.arange(10_000_000).sum()

49999995000000

In [11]:
%timeit sum([x for x in range(10_000_000)])

940 ms ± 67.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [12]:
# Ben Robin 7.7 
numbers = np.arange(1, 6)
numbers

array([1, 2, 3, 4, 5])

In [13]:
numbers * 2 

array([ 2,  4,  6,  8, 10])

In [14]:
numbers ** 3

array([  1,   8,  27,  64, 125])

In [15]:
numbers

array([1, 2, 3, 4, 5])

In [16]:
numbers*[2,2,2,2,2]

array([ 2,  4,  6,  8, 10])

In [17]:
numbers2 = np.linspace(1.1, 5.5, 5)
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [18]:
numbers * numbers2

array([ 1.1,  4.4,  9.9, 17.6, 27.5])

In [19]:
numbers

array([1, 2, 3, 4, 5])

In [20]:
numbers >=13

array([False, False, False, False, False])

In [21]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [22]:
numbers == numbers2

array([False, False, False, False, False])

In [24]:
numbers == numbers

array([ True,  True,  True,  True,  True])

In [25]:
#7.7 Ben Robin Self Check 
np.arange(1,6) **2 

array([ 1,  4,  9, 16, 25])