In [1]:
# Ben Robin 7.8 

In [3]:
pip install numpy

     |████████████████████████████████| 15.7 MB 7.1 MB/s            
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
grades = np.array([[87,96,70],[100,87,90],
                   [94,77,90],[100,81,82]])
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [6]:
grades.sum()

1054

In [7]:
grades.min()

70

In [8]:
grades.max()

100

In [9]:
grades.mean()

87.83333333333333

In [10]:
grades.std()

8.792357792739987

In [11]:
grades.std()

8.792357792739987

In [12]:
grades.var()

77.30555555555556

In [13]:
grades.mean(axis=0)

array([95.25, 85.25, 83.  ])

In [14]:
grades.mean(axis=1)

array([84.33333333, 92.33333333, 87.        , 87.66666667])

In [15]:
grades = np.random.randint(60,101,12).reshape(3,4)
grades

array([[95, 66, 93, 99],
       [92, 74, 82, 67],
       [97, 74, 68, 99]])

In [16]:
grades.mean()

83.83333333333333

In [17]:
grades.mean(axis=0)

array([94.66666667, 71.33333333, 81.        , 88.33333333])

In [18]:
grades.mean(axis=1)

array([88.25, 78.75, 84.5 ])

In [22]:
numbers = np.array([1,4,9,16,25,36])
np.sqrt(numbers)

array([1., 2., 3., 4., 5., 6.])

In [23]:
numbers2 = np.arange(1,7)*10
numbers2

array([10, 20, 30, 40, 50, 60])

In [24]:
np.add(numbers,numbers2)

array([11, 24, 39, 56, 75, 96])

In [25]:
np.multiply(numbers2,5)

array([ 50, 100, 150, 200, 250, 300])

In [29]:
numbers3 = numbers2.reshape(2,3)
numbers3

array([[10, 20, 30],
       [40, 50, 60]])

In [31]:
numbers4 = np.array([2,4,6])
np.multiply(numbers3, numbers4)

array([[ 20,  80, 180],
       [ 80, 200, 360]])

In [33]:
# Ben Robin 7.9 self check
numbers = np.arange(1,6)
np.power(numbers, 3)

array([  1,   8,  27,  64, 125])

In [34]:
grades = np.array([[87,96,70], [100,87,90],
                   [94,77,90], [100,81,82]])
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [35]:
grades[0,1]

96

In [36]:
grades[1]

array([100,  87,  90])

In [38]:
grades[0:2]

array([[ 87,  96,  70],
       [100,  87,  90]])

In [39]:
grades[[1,3]]

array([[100,  87,  90],
       [100,  81,  82]])

In [40]:
grades[:,0]

array([ 87, 100,  94, 100])

In [41]:
grades[:,1:3]

array([[96, 70],
       [87, 90],
       [77, 90],
       [81, 82]])

In [43]:
grades[:,[0,2]]

array([[ 87,  70],
       [100,  90],
       [ 94,  90],
       [100,  82]])

In [44]:
# Ben Robin 7.10 self check

In [45]:
a = np.arange(1,16).reshape(3,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [46]:
a[1]

array([ 6,  7,  8,  9, 10])

In [47]:
a[[0,2]]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [48]:
a[:,1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [49]:
# Ben Robin 7.11 
numbers = np.arange(1,6)
numbers

array([1, 2, 3, 4, 5])

In [50]:
numbers2 = numbers.view()

In [51]:
numbers2

array([1, 2, 3, 4, 5])

In [52]:
id(numbers)

140360910749584

In [53]:
id(numbers2)

140360910766800

In [54]:
numbers[1] *=10

In [55]:
numbers2

array([ 1, 20,  3,  4,  5])

In [56]:
numbers

array([ 1, 20,  3,  4,  5])

In [57]:
numbers2[1] /=10

In [58]:
numbers

array([1, 2, 3, 4, 5])

In [59]:
numbers2

array([1, 2, 3, 4, 5])

In [62]:
numbers2=numbers[0:3]
numbers2

array([1, 2, 3])

In [64]:
id(numbers)

140360910749584

In [65]:
id(numbers2)

140360910295664

In [66]:
numbers2[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [67]:
numbers[1] *=20

In [68]:
numbers

array([ 1, 40,  3,  4,  5])

In [69]:
numbers2

array([ 1, 40,  3])

In [70]:
# Ben Robin 7.12 

In [71]:
numbers = np.arange(1,6)
numbers

array([1, 2, 3, 4, 5])

In [72]:
numbers2 = numbers.copy()

In [73]:
numbers2

array([1, 2, 3, 4, 5])

In [74]:
numbers[1] *=10

In [75]:
numbers

array([ 1, 20,  3,  4,  5])

In [76]:
numbers2

array([1, 2, 3, 4, 5])

In [77]:
# 7.13 Ben Robin 

In [78]:
grades = np.array([[87,96,70], [100,87,90]])
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [79]:
grades.reshape(1,6)

array([[ 87,  96,  70, 100,  87,  90]])

In [80]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [81]:
grades.resize(1,6)
grades

array([[ 87,  96,  70, 100,  87,  90]])

In [82]:
grades = np.array([[87,96,70], [100,87,90]])
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [83]:
flattened = grades.flatten()

In [84]:
flattened

array([ 87,  96,  70, 100,  87,  90])

In [85]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [86]:
flattened[0] =100

In [87]:
flattened

array([100,  96,  70, 100,  87,  90])

In [88]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [89]:
raveled = grades.ravel()
raveled

array([ 87,  96,  70, 100,  87,  90])

In [90]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [91]:
raveled[0] = 100
raveled

array([100,  96,  70, 100,  87,  90])

In [92]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

In [93]:
grades.T

array([[100, 100],
       [ 96,  87],
       [ 70,  90]])

In [94]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

In [95]:
grades2 = np.array([[94,77,90], [100,81,82]])

In [96]:
np.hstack((grades, grades2))

array([[100,  96,  70,  94,  77,  90],
       [100,  87,  90, 100,  81,  82]])

In [97]:
np.vstack((grades,grades2))

array([[100,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [101]:
# 7.13 Ben Robin self check 
a = np.arange(1,7).reshape(2,3)

a = np.hstack((a, a))

a = np.vstack((a, a))

a

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [102]:
# 7.14 Ben Robin 

import pandas as pd 
grades = pd.Series([87, 100, 94])

ModuleNotFoundError: No module named 'pandas'

In [103]:
pip install pandas

     |████████████████████████████████| 11.3 MB 9.0 MB/s            
Note: you may need to restart the kernel to use updated packages.


In [105]:
import pandas as pd 
grades = pd.Series([87, 100, 94])
grades

0     87
1    100
2     94
dtype: int64

In [106]:
pd.Series(98.6,range(3))

0    98.6
1    98.6
2    98.6
dtype: float64

In [107]:
grades.count()

3

In [108]:
grades.mean()

93.66666666666667

In [109]:
grades.max()

100

In [110]:
grades.std()

6.506407098647712

In [111]:
grades.describe()

count      3.000000
mean      93.666667
std        6.506407
min       87.000000
25%       90.500000
50%       94.000000
75%       97.000000
max      100.000000
dtype: float64

In [114]:
grades = pd.Series({'Wally':87, 'Eva':100, 'Sam':94})
grades

Wally     87
Eva      100
Sam       94
dtype: int64

In [117]:
grades = pd.Series([87,100,94], index=['Wally','Eva','Sam'])
grades

Wally     87
Eva      100
Sam       94
dtype: int64

In [119]:
grades['Eva']

100

In [120]:
grades.Wally

87

In [121]:
grades.dtype

dtype('int64')

In [122]:
hardware = pd.Series(['Hammer', 'Saw','Wrench'])

In [123]:
hardware

0    Hammer
1       Saw
2    Wrench
dtype: object

In [125]:
hardware.str.contains('a')

0     True
1     True
2    False
dtype: bool

In [127]:
#7.14 self check Ben Robin

In [128]:
temps = np.random.randint(60,101,6)
temperatures = pd.Series(temps)
temperatures

0    65
1    60
2    90
3    62
4    96
5    77
dtype: int64

In [129]:
temperatures.min()

60

In [130]:
temperatures.max()

96

In [131]:
temperatures.mean()

75.0

In [132]:
temperatures.describe()

count     6.000000
mean     75.000000
std      15.257785
min      60.000000
25%      62.750000
50%      71.000000
75%      86.750000
max      96.000000
dtype: float64

In [142]:
import pandas as pd

In [143]:
#7.14.2 Data Frames Ben Robin 


grades_dict = {'Wally': [87,96,70], 'Eva':[100,87,90],
               'Sam': [94,77,90], 'Katie':[100,81,82],
               'Bob':[83,65,85]}

grades = pd.DataFrame(grades_dict)

grades
        
            

Wally  Eva  Sam  Katie  Bob
0     87  100   94    100   83
1     96   87   77     81   65
2     70   90   90     82   85

In [145]:
grades.index= ['Test1', 'Test2', 'Test3']
grades

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85

In [146]:
grades['Eva']

Test1    100
Test2     87
Test3     90
Name: Eva, dtype: int64

In [147]:
grades.Sam

Test1    94
Test2    77
Test3    90
Name: Sam, dtype: int64

In [148]:
grades.loc['Test1']

Wally     87
Eva      100
Sam       94
Katie    100
Bob       83
Name: Test1, dtype: int64

In [149]:
grades.iloc[1]

Wally    96
Eva      87
Sam      77
Katie    81
Bob      65
Name: Test2, dtype: int64

In [150]:
grades.loc['Test1':'Test3']

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85

In [152]:
grades.iloc[0:2]

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65

In [153]:
grades.loc[['Test1','Test3']]

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test3     70   90   90     82   85

In [155]:
grades.loc['Test1':'Test2',['Eva','Katie']]

Eva  Katie
Test1  100    100
Test2   87     81

In [156]:
grades.iloc[[0,2],0:3]

Wally  Eva  Sam
Test1     87  100   94
Test3     70   90   90

In [158]:
grades[grades >=90]

Wally    Eva   Sam  Katie  Bob
Test1    NaN  100.0  94.0  100.0  NaN
Test2   96.0    NaN   NaN    NaN  NaN
Test3    NaN   90.0  90.0    NaN  NaN

In [159]:
grades[(grades >=80) & (grades <90)]

Wally   Eva  Sam  Katie   Bob
Test1   87.0   NaN  NaN    NaN  83.0
Test2    NaN  87.0  NaN   81.0   NaN
Test3    NaN   NaN  NaN   82.0  85.0

In [163]:
grades.at['Test2', 'Eva'] 

87

In [166]:
grades.at['Test2','Eva'] = 100
grades.at['Test2','Eva']

100

In [167]:
grades.iat[1,2]=87
grades.iat[1,2]

87

In [169]:
grades.describe()

Wally         Eva        Sam       Katie        Bob
count   3.000000    3.000000   3.000000    3.000000   3.000000
mean   84.333333   96.666667  90.333333   87.666667  77.666667
std    13.203535    5.773503   3.511885   10.692677  11.015141
min    70.000000   90.000000  87.000000   81.000000  65.000000
25%    78.500000   95.000000  88.500000   81.500000  74.000000
50%    87.000000  100.000000  90.000000   82.000000  83.000000
75%    91.500000  100.000000  92.000000   91.000000  84.000000
max    96.000000  100.000000  94.000000  100.000000  85.000000

In [171]:
pd.set_option('precision',2)
grades.describe()

Wally     Eva    Sam   Katie    Bob
count   3.00    3.00   3.00    3.00   3.00
mean   84.33   96.67  90.33   87.67  77.67
std    13.20    5.77   3.51   10.69  11.02
min    70.00   90.00  87.00   81.00  65.00
25%    78.50   95.00  88.50   81.50  74.00
50%    87.00  100.00  90.00   82.00  83.00
75%    91.50  100.00  92.00   91.00  84.00
max    96.00  100.00  94.00  100.00  85.00

In [173]:
grades.mean()

Wally    84.33
Eva      96.67
Sam      90.33
Katie    87.67
Bob      77.67
dtype: float64

In [174]:
grades.T

Test1  Test2  Test3
Wally     87     96     70
Eva      100    100     90
Sam       94     87     90
Katie    100     81     82
Bob       83     65     85

In [176]:
grades.T.describe()

Test1   Test2  Test3
count    5.00    5.00   5.00
mean    92.80   85.80  83.40
std      7.66   13.81   8.23
min     83.00   65.00  70.00
25%     87.00   81.00  82.00
50%     94.00   87.00  85.00
75%    100.00   96.00  90.00
max    100.00  100.00  90.00

In [178]:
grades.T.mean()

Test1    92.8
Test2    85.8
Test3    83.4
dtype: float64

In [179]:
grades.sort_index(ascending=False)

Wally  Eva  Sam  Katie  Bob
Test3     70   90   90     82   85
Test2     96  100   87     81   65
Test1     87  100   94    100   83

In [180]:
grades.sort_index(axis=1)

Bob  Eva  Katie  Sam  Wally
Test1   83  100    100   94     87
Test2   65  100     81   87     96
Test3   85   90     82   90     70

In [182]:
grades.sort_values(by='Test1',axis=1,ascending=False)

Eva  Katie  Sam  Wally  Bob
Test1  100    100   94     87   83
Test2  100     81   87     96   65
Test3   90     82   90     70   85

In [184]:
grades.T.sort_values(by='Test1',ascending=False)

Test1  Test2  Test3
Eva      100    100     90
Katie    100     81     82
Sam       94     87     90
Wally     87     96     70
Bob       83     65     85

In [185]:
grades.loc['Test1'].sort_values(ascending=False)

Eva      100
Katie    100
Sam       94
Wally     87
Bob       83
Name: Test1, dtype: int64

In [190]:
#7.14 self check 

temps = {'Mon':[68,89], 'Tue':[71,93], 'Wed':[66,82], 'Thu':[75,97], 'Fri':[62,79]}
temperatures = pd.DataFrame(temps, index=['Low','High'])
temperatures

Mon  Tue  Wed  Thu  Fri
Low    68   71   66   75   62
High   89   93   82   97   79

In [191]:
temperatures.loc['Low']

Mon    68
Tue    71
Wed    66
Thu    75
Fri    62
Name: Low, dtype: int64

In [192]:
pd.set_option('precision',2)
temperatures.mean()

Mon    78.5
Tue    82.0
Wed    74.0
Thu    86.0
Fri    70.5
dtype: float64

In [193]:
temperatures.mean(axis=1)

Low     68.4
High    88.0
dtype: float64